# Testing Profile Configuration
app:
  environment: testing
  mock-data:
    enabled: true

logging:
  level:
    com.footballdynasty: DEBUG
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fd_db}
    username: ${DB_USERNAME:fd_user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true