spring:
  application:
    name: football-dynasty-api
  lifecycle:
    timeout-per-shutdown-phase: 10s
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fd_db
    username: fd_user
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  # SQL initialization disabled - using custom TeamInitializationService instead
  # sql:
  #   init:
  #     mode: embedded  
  #     data-locations: classpath:cfb_teams.sql
  #     continue-on-error: false

server:
  port: 8080
  servlet:
    context-path: /api/v2
  shutdown: immediate

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.footballdynasty: DEBUG
    org.springframework.security: DEBUG

# JWT Configuration
jwt:
  secret: mySecretKeyForFootballDynastyApplicationThatIsLongEnoughForHS256Algorithm
  expiration: 86400000 # 24 hours in milliseconds

# Environment Configuration
app:
  environment: development
  mock-data:
    enabled: false

# Sentry Configuration
sentry:
  dsn: ${SENTRY_DSN:https://50fabe156e12c01058ada4d3160a76f3@o4509526142681088.ingest.us.sentry.io/4509526245769216}
  environment: ${SPRING_PROFILES_ACTIVE:development}
  release: @project.version@
  traces-sample-rate: 1.0
  debug: true
  send-default-pii: true
  max-breadcrumbs: 100
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  exception-resolver-order: -2147483647