# Development Profile Configuration
app:
  environment: development
  mock-data:
    enabled: false

logging:
  level:
    com.footballdynasty: DEBUG
    org.springframework.security: DEBUG

spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s
  datasource:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  shutdown: immediate